### PR TITLE
 Application Gateway without WAF block.

### PR DESCRIPTION
**Pull request by harkirat22**
As per the Azure Best Practices. Found that Checkov scan didn't find this misconfiguration

### CODE REVIEW

**Comment by schosterbarak** [comment]
Thanks @harkirat22 . would you like to contribute that piece to checkov?

**Comment by harkirat22** [comment]
Yes. Always up for contributions.

**Comment by schosterbarak** [comment]
@harkirat22 very cool.
We've done a short guide on it: https://www.checkov.io/5.Contribution/New-Check.html
Also, you are invited to join http://slack.bridgecrew.io/ and talk with @metahertz or myself if you want to ask a question along the way.

**Comment by harkirat22** [comment]
Thank you @schosterbarak for the invite. I'll read the guide and do the contribution. Moreover, there are a couple of more checks that I have documented in my notes and they need to be in checkov.

**Comment by schosterbarak** [comment]
@harkirat22  please do. feel free to reach out :)

**Comment by metahertz** [comment]
Echoing @schosterbarak, Thanks for raising this and feel free to reach out to either of us with any issues or questions working with the Checkov codebase! Copying existing similar checks and matching tests are a great starting point after https://www.checkov.io/5.Contribution/New-Check.html :)

**Pull request merged**
